### ISSUE TITLE
Include school quotes on speaking page

### ISSUE THREAD

**Issue by dhood** [dhood/dhood.github.io#7]
I'd like to add these quotes from schools about my school talks to the [#speaking page](http://dhood.io/#speaking). Perhaps in place of the "Learning about the opportunities ..." block quote, [with a slideshow
](https://www.w3schools.com/howto/howto_js_slideshow.asp)
@CharlzGaldo are you interested?

![1](https://github.com/dhood/dhood.github.io/assets/5618076/89811792-b187-4d84-9d28-8a5fed6e8770)
![2](https://github.com/dhood/dhood.github.io/assets/5618076/7a1eece3-4a5d-491c-a7e1-695d39251811)
![3](https://github.com/dhood/dhood.github.io/assets/5618076/1ffc5f78-d6b6-40c5-9838-2ff4fe169872)
![4](https://github.com/dhood/dhood.github.io/assets/5618076/70a927fa-1ef3-4f18-9bed-55e13611ce01)
![5](https://github.com/dhood/dhood.github.io/assets/5618076/eb787af9-824e-49d6-93fb-3444ea4bcf32)
![6](https://github.com/dhood/dhood.github.io/assets/5618076/bf254b20-2fb7-4e57-b06c-5900d011d75a)
![7](https://github.com/dhood/dhood.github.io/assets/5618076/b3489cd0-2ee7-4914-864e-de9950671323)

**Comment by CharlzGaldo** [comment]
Sounds great miss! I am (sadly) going to be a little busier since year 12 has started and I also have to go to work, but, I'll still have plenty of time on the weekends to work on this 👍  or also at school lunches since I have a laptop 😁 but just a heads up that I'm still interested and would love to work on this! LMK if you need them done quicker and I can definitely plan something out to manage my time. Sorry for the inconvenience! 🙏

**Comment by dhood** [comment]
added in #8 ! :raised_hands:
